[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/search"
  to = "/.netlify/functions/api/search"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
